In [1]:
import numpy as np

#### 1. Create a 3x3 array that contains a diagonal of nines.

In [18]:
np.identity(3)*9

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

#### 2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [27]:
arr = np.array(range(2,33,2)).reshape(4,4)
print(arr)
l = np.mean(arr) - 0.5 * np.std(arr)
r = np.mean(arr) + 0.5 * np.std(arr)
print("\n")

print(arr[(arr >= l) & (arr <= r)])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


[14 16 18 20]


#### 3. Create a 9x9 array that contains only zero of type int.


In [29]:
np.zeros((9,9),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [33]:
n = int(input("Enter a number : "))
print(np.ones((n,n)) * np.arange(1,n+1))

Enter a number :  5


[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


## [5]

In [37]:
n = int(input())
cards = np.array(list(map(int, input().split())))

s, d, l, r, t = 0, 0, 0, n - 1, False

while l <= r:
    if cards[l] >= cards[r]:
        card = cards[l]
        l += 1
    else:
        card = cards[r]
        r -= 1
    if not t :
        s += card
    else:
        d += card
    t = not t
    
print (s, d)

 4
 4 1 2 10


12 5


## [6]

In [57]:
import numpy as np
n, m = map(int, input().split())
p = np.array([input().strip().split() for row in range(n)])
colors = ['C', 'M', 'Y']
if np.isin(p, colors).any():
    print('#Color')
else:
    print('#Black&White')

 3 2
 W W
 W W
 B B


#Black&White
